name: 'Test build'
on: 
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
     
      - name: 'Setup go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      
      - name: 'Resolve dependencies'
        run: go mod tidy
      
      - name: 'Build'
        run: go build -v .
