name: 'Test build'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: 'Build'
        run: pwd && ls -l .. && go build -v .
